### ISSUE TITLE
HashTable_GPU.py  code error

### ISSUE THREAD

**Issue by woshituobaye** [SamuelJoutard/Permutohedral_attention_module#2]
![image](https://user-images.githubusercontent.com/20101085/67072040-a2d94280-f1b6-11e9-9f25-67ecacea8b5f.png)
![image](https://user-images.githubusercontent.com/20101085/67072372-4aef0b80-f1b7-11e9-955b-030f6dfa55bf.png)

 can not find the method cuda.LongTensor()   cuda.floatTensor()  torch.sparse.LongTensor()

**Comment by SamuelJoutard** [comment]
Hello,

Could you elaborate? What is the error exactly? Which version of Pytorch do you have?
You can find informations about the Cuda tensor types here:
https://pytorch.org/docs/stable/tensors.html
and about the sparse API here:
https://pytorch.org/docs/stable/sparse.html

Samuel
